export enum ReduxConstants {
  PRESET_STORE_SYNCED = 'PRESET_STORE_SYNCED',
  PRESET_PRODUCTS = 'PRESET_PRODUCTS',
  SET_PRODUCTS = 'SET_PRODUCTS',
  PRESET_SELECTED_PRODUCT = 'PRESET_SELECTED_PRODUCT',
  SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT',
  SET_PRODUCT_VARIANT = 'SET_PRODUCT_VARIANT',
  SET_QUANTITY_INCREMENT = 'SET_QUANTITY_INCREMENT',
  SET_QUANTITY_DECREMENT = 'SET_QUANTITY_DECREMENT',
}

export default ReduxConstants;
